version: '3.8'

services:
  github-integration-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    stdin_open: true
    tty: true

  github-integration-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    stdin_open: true
    tty: true

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - appnet
