//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class GitHubClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "http://localhost:8080";
    }

    getLive(): Observable<ApiResponseOfLiveCommitsDto> {
        let url_ = this.baseUrl + "/api/GitHub/live";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetLive(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetLive(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ApiResponseOfLiveCommitsDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ApiResponseOfLiveCommitsDto>;
        }));
    }

    protected processGetLive(response: HttpResponseBase): Observable<ApiResponseOfLiveCommitsDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ApiResponseOfLiveCommitsDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getScheduled(searchText: string | null | undefined, startDate: Date | null | undefined, endDate: Date | null | undefined, page: number | undefined, pageSize: number | undefined): Observable<ApiResponseOfScheduledCommitsDto> {
        let url_ = this.baseUrl + "/api/GitHub/scheduled?";
        if (searchText !== undefined && searchText !== null)
            url_ += "searchText=" + encodeURIComponent("" + searchText) + "&";
        if (startDate !== undefined && startDate !== null)
            url_ += "startDate=" + encodeURIComponent(startDate ? "" + startDate.toISOString() : "") + "&";
        if (endDate !== undefined && endDate !== null)
            url_ += "endDate=" + encodeURIComponent(endDate ? "" + endDate.toISOString() : "") + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetScheduled(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetScheduled(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ApiResponseOfScheduledCommitsDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ApiResponseOfScheduledCommitsDto>;
        }));
    }

    protected processGetScheduled(response: HttpResponseBase): Observable<ApiResponseOfScheduledCommitsDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ApiResponseOfScheduledCommitsDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class ApiResponseOfLiveCommitsDto implements IApiResponseOfLiveCommitsDto {
    success?: boolean;
    message?: string;
    data?: LiveCommitsDto | undefined;

    constructor(data?: IApiResponseOfLiveCommitsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            this.data = _data["data"] ? LiveCommitsDto.fromJS(_data["data"]) : undefined as any;
        }
    }

    static fromJS(data: any): ApiResponseOfLiveCommitsDto {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfLiveCommitsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        data["data"] = this.data ? this.data.toJSON() : undefined as any;
        return data;
    }
}

export interface IApiResponseOfLiveCommitsDto {
    success?: boolean;
    message?: string;
    data?: LiveCommitsDto | undefined;
}

export class PagedResultOfGitHubCommitDto implements IPagedResultOfGitHubCommitDto {
    items?: GitHubCommitDto[];
    totalCount?: number;

    constructor(data?: IPagedResultOfGitHubCommitDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(GitHubCommitDto.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
        }
    }

    static fromJS(data: any): PagedResultOfGitHubCommitDto {
        data = typeof data === 'object' ? data : {};
        let result = new PagedResultOfGitHubCommitDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["totalCount"] = this.totalCount;
        return data;
    }
}

export interface IPagedResultOfGitHubCommitDto {
    items?: GitHubCommitDto[];
    totalCount?: number;
}

export class LiveCommitsDto extends PagedResultOfGitHubCommitDto implements ILiveCommitsDto {

    constructor(data?: ILiveCommitsDto) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): LiveCommitsDto {
        data = typeof data === 'object' ? data : {};
        let result = new LiveCommitsDto();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface ILiveCommitsDto extends IPagedResultOfGitHubCommitDto {
}

export class GitHubCommitDto implements IGitHubCommitDto {
    sha?: string | undefined;
    authorName?: string | undefined;
    authorEmail?: string | undefined;
    date?: Date;
    message?: string | undefined;
    htmlUrl?: string | undefined;
    source?: string | undefined;

    constructor(data?: IGitHubCommitDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.sha = _data["sha"];
            this.authorName = _data["authorName"];
            this.authorEmail = _data["authorEmail"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : undefined as any;
            this.message = _data["message"];
            this.htmlUrl = _data["htmlUrl"];
            this.source = _data["source"];
        }
    }

    static fromJS(data: any): GitHubCommitDto {
        data = typeof data === 'object' ? data : {};
        let result = new GitHubCommitDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["sha"] = this.sha;
        data["authorName"] = this.authorName;
        data["authorEmail"] = this.authorEmail;
        data["date"] = this.date ? this.date.toISOString() : undefined as any;
        data["message"] = this.message;
        data["htmlUrl"] = this.htmlUrl;
        data["source"] = this.source;
        return data;
    }
}

export interface IGitHubCommitDto {
    sha?: string | undefined;
    authorName?: string | undefined;
    authorEmail?: string | undefined;
    date?: Date;
    message?: string | undefined;
    htmlUrl?: string | undefined;
    source?: string | undefined;
}

export class ApiResponseOfScheduledCommitsDto implements IApiResponseOfScheduledCommitsDto {
    success?: boolean;
    message?: string;
    data?: ScheduledCommitsDto | undefined;

    constructor(data?: IApiResponseOfScheduledCommitsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            this.data = _data["data"] ? ScheduledCommitsDto.fromJS(_data["data"]) : undefined as any;
        }
    }

    static fromJS(data: any): ApiResponseOfScheduledCommitsDto {
        data = typeof data === 'object' ? data : {};
        let result = new ApiResponseOfScheduledCommitsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        data["data"] = this.data ? this.data.toJSON() : undefined as any;
        return data;
    }
}

export interface IApiResponseOfScheduledCommitsDto {
    success?: boolean;
    message?: string;
    data?: ScheduledCommitsDto | undefined;
}

export class ScheduledCommitsDto extends PagedResultOfGitHubCommitDto implements IScheduledCommitsDto {
    lastSyncTime?: Date;

    constructor(data?: IScheduledCommitsDto) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.lastSyncTime = _data["lastSyncTime"] ? new Date(_data["lastSyncTime"].toString()) : undefined as any;
        }
    }

    static override fromJS(data: any): ScheduledCommitsDto {
        data = typeof data === 'object' ? data : {};
        let result = new ScheduledCommitsDto();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["lastSyncTime"] = this.lastSyncTime ? this.lastSyncTime.toISOString() : undefined as any;
        super.toJSON(data);
        return data;
    }
}

export interface IScheduledCommitsDto extends IPagedResultOfGitHubCommitDto {
    lastSyncTime?: Date;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}